### PR TITLE
Fix TOML booleans

### PR DESCRIPTION
**Pull request by kasium**
The main application logic assumes, that booleans are passed as strings from the config.
However, TOML supports native booleans which are obviously no strings.

The easiest solution is to translate bools to strings when parsing the TOML.

### CODE REVIEW

**Comment by kasium** [comment]
Buil fails with weird error:
```
(          readme: line    3) broken    https://travis-ci.com/seddonym/import-linter - 404 Client Error: Not Found for url: https://www.travis-ci.com/seddonym/import-linter
```

Can you please have a look?

**Comment by seddonym** [comment]
> Buil fails with weird error:

Could you try rebasing off the latest master? I think this might be fixed there.

**Comment by kasium** [comment]
The commit bases on 3dfc428301cc0c993d39102879cc06e083e3dfbb which should be the latest master

**Comment by seddonym** [comment]
Would you be able to try again? I've just merged a fix to master.

**Review by seddonym — CHANGES_REQUESTED** [review]
Thanks for spotting this! I think it makes more sense to change this [here](https://github.com/kasium/import-linter/blob/27e6bc6bfed41f4113f52c17c509e00fb03c43c4/src/importlinter/application/use_cases.py#L191), so we accept that `include_external_packages` could be a boolean too.

Ideally there would be a failing test that this commit causes to pass. I suggest adding an extra parameter to [this functional test](https://github.com/kasium/import-linter/blob/27e6bc6bfed41f4113f52c17c509e00fb03c43c4/tests/functional/test_lint_imports.py#L30) for a TOML version of the config - that should just be a case of a single line extra, plus making a copy of [this file](https://github.com/kasium/import-linter/blob/2cc9805880fdaca65c67b0e6db9e2e3931713a1c/tests/assets/testpackage/.externalkeptcontract.ini) and converting it to TOML:

```
(testpackage_directory, ".externalkeptcontract.toml", cli.EXIT_STATUS_SUCCESS),
```

Let me know if any questions.

**Comment by kasium** [comment]
Hi,

I added it in a very general way, since there are multiple boolean options like allow_indirect_imports or internal_external_packages. Also existing custom contracts might rely on the fact, that booleans are passed as strings.

Test can be added.

**Comment by seddonym** [comment]
> I added it in a very general way, since there are multiple boolean options like allow_indirect_imports or internal_external_packages. Also existing custom contracts might rely on the fact, that booleans are passed as strings.

Good point. I don't really like the way we handle booleans in the configuration as strings, instead we should probably have a `BooleanField`, but I think that's out of scope for this PR. Thanks for fixing!

**Review by seddonym — APPROVED** [review]

**Comment by kasium** [comment]
Thanks. I thought also about a BooleanField, but boolean handling is quite spreaded over the code, therefore it would be a little bit more.

**Pull request merged**
